applications:
  art-creation:
    type: php:8.2
    web:
      locations:
        "/":
          root: "public"
          index: ["index.php"]
          passthru: "/index.php"
    variables:
      env:
        APP_ENV: "prod"
        APP_DEBUG: "false"
        MONGO_URI: ""
        MONGO_APP_DB: ""
